### ISSUE TITLE
Undefined method `to_i' for #<Rails::Rack::LogTailer>

### ISSUE THREAD

**Issue by vrish88** [simonoff/golden_brindle#4]
When trying to use golden_brindle v0.3 with unicorn v4.1.1 an error occurs when you try and make a request.

```
app error: undefined method `to_i' for #<Rails::Rack::LogTailer:0x103547eb0> (NoMethodError)
  gems/unicorn-4.1.1/lib/unicorn/http_server.rb:532:in `process_client'
  gems/unicorn-4.1.1/lib/unicorn/http_server.rb:602:in `worker_loop'
  gems/unicorn-4.1.1/lib/unicorn/http_server.rb:485:in `spawn_missing_workers'
  gems/unicorn-4.1.1/lib/unicorn/http_server.rb:135:in `start'
  gems/golden_brindle-0.3/bin/../lib/golden_brindle/start.rb:124:in `run'
```

**Comment by vrish88** [comment]
I'm also using rack 1.1.2, fyi.

**Comment by simonoff** [comment]
What version of Rails are you used?

**Comment by simonoff** [comment]
And you tried run unicorn_rails inside your Rails app directory?

**Comment by vrish88** [comment]
I've tried it using rails v2.3.5 & v2.3.12 and unicorn_rails works in the app directory. Although I did have to downgrade rack to use v1.1.2 instead v1.2.0. Could the rack version affect it at all?

Also, sorry for being an idiot above and closing then reopening (twice). gah...

**Comment by simonoff** [comment]
Hm... I can reproduce this bug, but only on 1.8.7 ruby. On 1.9.2 all works fine. I will investigate this bug and post the progress there.
